/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * siswaForm.java
 *
 * Created on 15 Jun 13, 12:00:49
 */

package form;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author User
 */
public class dataSiswa extends javax.swing.JInternalFrame {
    
    Connection con;
    Statement st,st2;
    ResultSet rs;
    
    private String date;
    
    //--- Deklarasi Tabel ---\\
    DefaultTableModel tableModel = new DefaultTableModel();
    private String[] colom = {"NIS","Kelas","Tahun Angkatan","Nama Siswa","Tanggal Lahir","Alamat Siswa","JK","Agama",
                            "Nama Orangtua","Pekerjaan","Alamat Orangtua","Nomor Telfon"};
    private Object[][] dTabel = null;
    
    /** Creates new form siswaForm */
    public dataSiswa() {
        initComponents();
        ImageIcon icon = new ImageIcon(mainMenu.class.getResource("/gambar/siswa.png"));
        java.awt.Image image = icon.getImage();
        btnGrupJKSiswa.add(rbLaki);
        btnGrupJKSiswa.add(rbPeremuan);
        baca_data();
        tabelSiswa.setSize(880, 380);
        tabelSiswa.setResizable(false);
        tabelSiswa.setIconImage(image);
        tabelSiswa.setTitle("Tabel Keterangan Data Siswa");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - tabelSiswa.getSize().width)/2;
        int y = (dim.height - tabelSiswa.getSize().height)/2;
        tabelSiswa.setLocation(x,y);
        baca_data_tabel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnGrupJKSiswa = new javax.swing.ButtonGroup();
        tabelSiswa = new javax.swing.JDialog();
        buttonSetData = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelSiswaObjek = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        yearFilter = new com.toedter.calendar.JYearChooser();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaSiswa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNIS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPeremuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbAgama = new javax.swing.JComboBox();
        dateTanggalLahir = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        cmbKelasID = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNamaOrtu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbPekerjaan = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtNomorTelfon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamatOrtu = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        buttonSimpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        yearAngkatan = new com.toedter.calendar.JYearChooser();

        jLabel6.setText("jLabel6");

        buttonSetData.setText("Set Data");
        buttonSetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetDataActionPerformed(evt);
            }
        });

        tabelSiswaObjek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelSiswaObjek);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Filter Data Berdasarkan Tahun Angkatan");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        yearFilter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setText("Set");

        javax.swing.GroupLayout tabelSiswaLayout = new javax.swing.GroupLayout(tabelSiswa.getContentPane());
        tabelSiswa.getContentPane().setLayout(tabelSiswaLayout);
        tabelSiswaLayout.setHorizontalGroup(
            tabelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addGroup(tabelSiswaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(10, 10, 10)
                        .addComponent(yearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSetData)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
        );

        tabelSiswaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonSetData, jButton1});

        tabelSiswaLayout.setVerticalGroup(
            tabelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSetData)
                        .addComponent(jButton1)
                        .addComponent(jButton3))
                    .addComponent(yearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(14, 14, 14))
        );

        tabelSiswaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonSetData, jButton1});

        setClosable(true);
        setTitle("Form Siswa");
        setMinimumSize(new java.awt.Dimension(53, 33));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Form Data Siswa ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel2.setText("Nama");

        jLabel3.setText("NIS");

        txtNIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNISKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNISKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNISKeyTyped(evt);
            }
        });

        jLabel4.setText("Alamat");

        jLabel5.setText("Jenis Kelamin");

        rbLaki.setSelected(true);
        rbLaki.setText("Laki-Laki");

        rbPeremuan.setText("Perempuan");

        jLabel7.setText("Tanggal Lahir");

        jLabel8.setText("Agama");

        cmbAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih Agama ---", "Islam", "Kristen", "Katholik", "Hindu", "Budha" }));

        dateTanggalLahir.setDateFormatString("dd MMMM yyyy");
        dateTanggalLahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateTanggalLahirPropertyChange(evt);
            }
        });

        jLabel13.setText("Id Kelas");

        cmbKelasID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih ID Kelas ---", "Kelas 1", "Kelas 2", "Kelas 3", "Kelas 4", "Kelas 5", "Kelas 6" }));
        cmbKelasID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKelasIDActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setLineWrap(true);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbAgama, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateTanggalLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(rbLaki)
                            .addGap(29, 29, 29)
                            .addComponent(rbPeremuan)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamaSiswa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbKelasID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cmbKelasID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLaki)
                    .addComponent(jLabel5)
                    .addComponent(rbPeremuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(dateTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAgama)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Orang Tua "));
        jPanel2.setToolTipText("");

        jLabel9.setText("Nama Orang Tua");

        jLabel10.setText("Alamat");

        jLabel11.setText("Pekerjaan");

        cmbPekerjaan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih Pekerjaan ---", "PNS", "Wiraswasta", "Dagang", "Buruh", "Lain-Lain" }));

        jLabel12.setText("Nomor Telfon");

        txtNomorTelfon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomorTelfonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomorTelfonKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomorTelfonKeyTyped(evt);
            }
        });

        txtAlamatOrtu.setColumns(20);
        txtAlamatOrtu.setLineWrap(true);
        txtAlamatOrtu.setRows(5);
        jScrollPane2.setViewportView(txtAlamatOrtu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaOrtu, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNomorTelfon, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbPekerjaan, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaOrtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cmbPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNomorTelfon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(" Button"));

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Baru");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonSimpan, jButton2, jButton4, jButton5});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36));
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("FORM DATA SISWA");

        jButton6.setText("Lihat Data...");
        jButton6.setToolTipText("Lihat Tabel Siswa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setText("Tahun Ajaran");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        yearAngkatan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(421, 421, 421)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearAngkatan, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yearAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tabelSiswa.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

private void cmbKelasIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKelasIDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbKelasIDActionPerformed

private void dateTanggalLahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateTanggalLahirPropertyChange
// TODO add your handling code here:
    if(dateTanggalLahir.getDate() != null){
        String tanggal = "yyyy-MM-dd";
        SimpleDateFormat dateFormat = new SimpleDateFormat(tanggal);
        date = String.valueOf(dateFormat.format(dateTanggalLahir.getDate()));
    }
}//GEN-LAST:event_dateTanggalLahirPropertyChange

private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
// TODO add your handling code here:
    //--- Deklarasi untuk SISWA ---\\
    String nis = txtNIS.getText();
    String namaSiswa = txtNamaSiswa.getText();
    String alamatSiswa = txtAlamat.getText();
    String idKelas = cmbKelasID.getSelectedItem().toString();
    String jekel="";
    if(rbLaki.isSelected()){
        jekel = "L";
    }else{
        jekel = "P";
    }
    String agama = "";
    if(cmbAgama.getSelectedIndex() == 1){
        agama = "ISLAM";
    }else if(cmbAgama.getSelectedIndex() == 2){
        agama = "KRISTEN";
    }else if(cmbAgama.getSelectedIndex() == 3){
        agama = "KATHOLIK";
    }else if(cmbAgama.getSelectedIndex() == 4){
        agama = "HINDU";
    }else{
        agama = "BUDHA";
    }
    
    //--- Deklarasi Untuk Orang Tua ---\\
    String namaOrtu = txtNamaOrtu.getText();
    String alamatOrtu = txtAlamatOrtu.getText();
    String noTelfon = txtNomorTelfon.getText();
    String pekerjaan = "";
    if(cmbPekerjaan.getSelectedIndex() == 1){
        pekerjaan = "PNS";
    }else if(cmbPekerjaan.getSelectedIndex() == 2){
        pekerjaan = "Wiraswasta";
    }else if(cmbPekerjaan.getSelectedIndex() == 3){
        pekerjaan = "Dagang";
    }else if(cmbPekerjaan.getSelectedIndex() == 4){
        pekerjaan = "Buruh";
    }else{
        pekerjaan = "Lainnya";
    }
    int angkatan = yearAngkatan.getYear();
    
    //--- Validasi Siswa---\\
    if(nis.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Input NIS.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNIS.requestFocus();
    }else if(namaSiswa.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Nama Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNamaSiswa.requestFocus();
    }else if(alamatSiswa.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Alamat Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtAlamat.requestFocus();
    }else if(namaOrtu.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Nama Orangtua Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNamaOrtu.requestFocus();
    }else if(alamatOrtu.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Alamat Orangtua Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtAlamatOrtu.requestFocus();
    }else if(namaSiswa.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Nama Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNamaSiswa.requestFocus();
    }else if(noTelfon.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan No Telfon Orangtus Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNomorTelfon.requestFocus();
    }else if(cmbAgama.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Pilih Agama Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }else if(cmbPekerjaan.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Pekerjaan Orang Tua Wajib Dipilih.","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }else if(cmbKelasID.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Pilih Kelas.","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }else{
        try{
            st = con.createStatement();
            st2 = con.createStatement();
            String simpanSiswa = "INSERT INTO tbsiswa VALUES ('"+nis+"','"+idKelas+"','"+angkatan+"',"
                    + "'"+namaSiswa+"','"+date+"','"+alamatSiswa+"','"+jekel+"','"+agama+"')";
            String simpanOrtu = "INSERT INTO tbortu VALUES ('"+nis+"','"+namaOrtu+"','"+pekerjaan+"','"+alamatOrtu+"','"+noTelfon+"')";
            st.executeUpdate(simpanSiswa);
            st2.executeUpdate(simpanOrtu);
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan.","Informasi",JOptionPane.INFORMATION_MESSAGE);
            mati();
            baca_data_tabel();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan.\nData Gagal Disimpan.\nSilahkan Cek Data Kembali.","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
            e.printStackTrace();
        }
        
    }
}//GEN-LAST:event_buttonSimpanActionPerformed

private void txtNomorTelfonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomorTelfonKeyReleased
// TODO add your handling code here:
    String angka = txtNomorTelfon.getText();
    if(angka.matches("[0-9]*")){
    }else{
        JOptionPane.showMessageDialog(null, "Inputan Hanya Boleh Angka.","Peringatan",JOptionPane.WARNING_MESSAGE);
        txtNomorTelfon.setText(null);
        txtNomorTelfon.requestFocus();
    }
}//GEN-LAST:event_txtNomorTelfonKeyReleased

private void txtNISKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNISKeyReleased
// TODO add your handling code here:
    String angka = txtNIS.getText();
    if(angka.matches("[0-9]*")){
    }else{
        JOptionPane.showMessageDialog(null, "Inputan Hanya Boleh Angka.","Peringatan",JOptionPane.WARNING_MESSAGE);
        txtNIS.setText(null);
        txtNIS.requestFocus();
    }
}//GEN-LAST:event_txtNISKeyReleased

private void txtNISKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNISKeyPressed
// TODO add your handling code here:
    
}//GEN-LAST:event_txtNISKeyPressed

private void txtNomorTelfonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomorTelfonKeyPressed
// TODO add your handling code here:
    
}//GEN-LAST:event_txtNomorTelfonKeyPressed

private void txtNISKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNISKeyTyped
// TODO add your handling code here:
    
}//GEN-LAST:event_txtNISKeyTyped

private void txtNomorTelfonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomorTelfonKeyTyped
// TODO add your handling code here:
    
}//GEN-LAST:event_txtNomorTelfonKeyTyped

private void buttonSetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetDataActionPerformed
// TODO add your handling code here:
    try{
        int row = tabelSiswaObjek.getSelectedRow();
        String tampil = (tabelSiswaObjek.getModel().getValueAt(row, 0).toString());
        String setData = "SELECT tbsiswa.nis AS siswaNIS, tbsiswa.idkelas AS siswaKelas, tbsiswa.th_angkatan as siswaAngkatan,"
                    + "tbsiswa.nama_siswa AS siswaNama, tbsiswa.tanggal_lahir AS siswaTTL, tbsiswa.alamat_siswa AS siswaAlamat,"
                    + "tbsiswa.jenis_kelamin as siswaJekel, tbsiswa.agama_siswa AS siswaAgama, tbortu.nama_ortu AS ortuNama, tbortu.pekerjaan AS ortuPekerjaan,"
                    + "tbortu.alamat AS ortuAlamat, tbortu.telfon AS ortuTelfon FROM tbsiswa, tbortu WHERE tbsiswa.nis = '"+tampil+"'";
         st = con.prepareStatement(tampil);
         rs = st.executeQuery(setData);
         if(rs.next()){
             String nis = rs.getString("siswaNIS");
             txtNIS.setText(nis);
             if(rs.getString("siswaKelas").equals("Kelas 1")){
                 cmbKelasID.setSelectedIndex(1);
             }else if(rs.getString("siswaKelas").equals("Kelas 2")){
                 cmbKelasID.setSelectedIndex(2);
             }else if(rs.getString("siswaKelas").equals("Kelas 3")){
                 cmbKelasID.setSelectedIndex(3);
             }else if(rs.getString("siswaKelas").equals("Kelas 4")){
                 cmbKelasID.setSelectedIndex(4);
             }else if(rs.getString("siswaKelas").equals("Kelas 5")){
                 cmbKelasID.setSelectedIndex(5);
             }else if(rs.getString("siswaKelas").equals("Kelas 6")){
                 cmbKelasID.setSelectedIndex(6);
             }
             int tanggal = rs.getInt("siswaAngkatan");
             yearAngkatan.setYear(tanggal);
             if(rs.getString("siswaJekel").equals("L")){
                 rbLaki.setSelected(true);
             }else{
                 rbPeremuan.setSelected(true);
             }
             if(rs.getString("siswaAgama").equals("ISLAM")){
                cmbAgama.setSelectedIndex(1);
             }else if(rs.getString("siswaAgama").equals("KRISTEN")){
                cmbAgama.setSelectedIndex(2);
             }else if(rs.getString("siswaAgama").equals("KATHOLIK")){
                cmbAgama.setSelectedIndex(3);
             }else if(rs.getString("siswaAgama").equals("HINDU")){
                cmbAgama.setSelectedIndex(4);
             }else if(rs.getString("siswaAgama").equals("BUDHA")){
                cmbAgama.setSelectedIndex(5);
             }
             String nama = rs.getString("siswaNama");
             txtNamaSiswa.setText(nama);
             String alamatSiswa = rs.getString("siswaAlamat");
             txtAlamat.setText(alamatSiswa);
             Date tanggaLahir = rs.getDate("siswaTTL");
             dateTanggalLahir.setDate(tanggaLahir);
             String namaOrtu = rs.getString("ortuNama");
             txtNamaOrtu.setText(namaOrtu);
             String alamatOrtu = rs.getString("ortuAlamat");
             txtAlamatOrtu.setText(alamatOrtu);
             String telfonOrtu = rs.getString("ortuTelfon");
             txtNomorTelfon.setText(telfonOrtu);
             if(rs.getString("ortuPekerjaan").equals("PNS")){
                 cmbPekerjaan.setSelectedIndex(1);
             }else if(rs.getString("ortuPekerjaan").equals("Wiraswasta")){
                 cmbPekerjaan.setSelectedIndex(2);
             }else if(rs.getString("ortuPekerjaan").equals("Dagang")){
                 cmbPekerjaan.setSelectedIndex(3);
             }else if(rs.getString("ortuPekerjaan").equals("Buruh")){
                 cmbPekerjaan.setSelectedIndex(4);
             }else if(rs.getString("ortuPekerjaan").equals("Lainnya")){
                 cmbPekerjaan.setSelectedIndex(5);
             }
         }
         tabelSiswa.dispose();
    }catch(Exception e){
        System.out.println(e);
        e.printStackTrace();
    }
}//GEN-LAST:event_buttonSetDataActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    mati();
    txtNIS.requestFocus();
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    int confirmasi = JOptionPane.showConfirmDialog(null, 
            "Yakin Ingin Menghapus Data Ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
    if(confirmasi == 0){
        try{
            st = con.createStatement();
            st2 = con.createStatement();
            String hapus = "DELETE FROM tbsiswa WHERE nis = "
                    + "'"+tabelSiswaObjek.getValueAt(tabelSiswaObjek.getSelectedRow(), 0).toString() +"'";
            String hapus2 = "DELETE FROM tbortu WHERE telfon = "
                    + "'"+tabelSiswaObjek.getValueAt(tabelSiswaObjek.getSelectedRow(), 11).toString() +"'";
            st.executeUpdate(hapus);
            st2.executeUpdate(hapus2);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus.","Informasi",JOptionPane.INFORMATION_MESSAGE);
            baca_data_tabel();
            mati();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Dihapus. Pilih Item Terlebih Dahulu","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    //--- Deklarasi untuk SISWA ---\\
    String nis = txtNIS.getText();
    String namaSiswa = txtNamaSiswa.getText();
    String alamatSiswa = txtAlamat.getText();
    String idKelas = cmbKelasID.getSelectedItem().toString();
    String jekel="";
    if(rbLaki.isSelected()){
        jekel = "L";
    }else{
        jekel = "P";
    }
    String agama = "";
    if(cmbAgama.getSelectedIndex() == 1){
        agama = "ISLAM";
    }else if(cmbAgama.getSelectedIndex() == 2){
        agama = "KRISTEN";
    }else if(cmbAgama.getSelectedIndex() == 3){
        agama = "KATHOLIK";
    }else if(cmbAgama.getSelectedIndex() == 4){
        agama = "HINDU";
    }else{
        agama = "BUDHA";
    }
    
    //--- Deklarasi Untuk Orang Tua ---\\
    String namaOrtu = txtNamaOrtu.getText();
    String alamatOrtu = txtAlamatOrtu.getText();
    String noTelfon = txtNomorTelfon.getText();
    String pekerjaan = "";
    if(cmbPekerjaan.getSelectedIndex() == 1){
        pekerjaan = "PNS";
    }else if(cmbPekerjaan.getSelectedIndex() == 2){
        pekerjaan = "Wiraswasta";
    }else if(cmbPekerjaan.getSelectedIndex() == 3){
        pekerjaan = "Dagang";
    }else if(cmbPekerjaan.getSelectedIndex() == 4){
        pekerjaan = "Buruh";
    }else{
        pekerjaan = "Lainnya";
    }
    int angkatan = yearAngkatan.getYear();
    
    //--- Validasi Siswa---\\
    if(nis.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Input NIS.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNIS.requestFocus();
    }else if(namaSiswa.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Nama Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNamaSiswa.requestFocus();
    }else if(alamatSiswa.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Alamat Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtAlamat.requestFocus();
    }else if(namaOrtu.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Nama Orangtua Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNamaOrtu.requestFocus();
    }else if(alamatOrtu.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Alamat Orangtua Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtAlamatOrtu.requestFocus();
    }else if(namaSiswa.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Nama Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNamaSiswa.requestFocus();
    }else if(noTelfon.equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan No Telfon Orangtus Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtNomorTelfon.requestFocus();
    }else if(cmbAgama.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Pilih Agama Siswa.","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }else if(cmbPekerjaan.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Pekerjaan Orang Tua Wajib Dipilih.","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }else if(cmbKelasID.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Pilih Kelas.","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }else{
        try{
            st = con.createStatement();
            st2 = con.createStatement();
            String simpanSiswa = "UPDATE tbsiswa SET tbsiswa.nis = '"+nis+"', tbsiswa.idkelas = '"+idKelas+"',tbsiswa.th_angkatan='"+angkatan+"',"
                    + "tbsiswa.nama_siswa='"+namaSiswa+"',tbsiswa.tanggal_lahir='"+date+"',tbsiswa.alamat_siswa = '"+alamatSiswa+"',"
                    + "tbsiswa.jenis_kelamin = '"+jekel+"',tbsiswa.agama_siswa = '"+agama+"' WHERE tbsiswa.nis = '"+nis+"'";
            String simpanOrtu = "UPDATE tbortu SET tbortu.nis = '"+nis+"',tbortu.nama_ortu = '"+namaOrtu+"',"
                    + "tbortu.pekerjaan = '"+pekerjaan+"',tbortu.alamat = '"+alamatOrtu+"',tbortu.telfon = '"+noTelfon+"' WHERE tbortu.nis = '"+nis+"'";
            st.executeUpdate(simpanSiswa);
            st2.executeUpdate(simpanOrtu);
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate.","Informasi",JOptionPane.INFORMATION_MESSAGE);
            mati();
            baca_data_tabel();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan.\nData Gagal Diupdate.\nSilahkan Cek Data Kembali.","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
            e.printStackTrace();
        }
    }
}//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupJKSiswa;
    private javax.swing.JButton buttonSetData;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox cmbAgama;
    private javax.swing.JComboBox cmbKelasID;
    private javax.swing.JComboBox cmbPekerjaan;
    private com.toedter.calendar.JDateChooser dateTanggalLahir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPeremuan;
    private javax.swing.JDialog tabelSiswa;
    private javax.swing.JTable tabelSiswaObjek;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextArea txtAlamatOrtu;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNamaOrtu;
    private javax.swing.JTextField txtNamaSiswa;
    private javax.swing.JTextField txtNomorTelfon;
    private com.toedter.calendar.JYearChooser yearAngkatan;
    private com.toedter.calendar.JYearChooser yearFilter;
    // End of variables declaration//GEN-END:variables

    private void baca_data(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost/visual", "root", "");
            st = con.createStatement();            
            System.out.println("Koneksi Sukses");
        } catch (SQLException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void mati(){
        txtNIS.setText(null);
        txtAlamat.setText(null);
        txtAlamatOrtu.setText(null);
        txtNamaOrtu.setText(null);
        txtNamaSiswa.setText(null);
        txtNomorTelfon.setText(null);
        dateTanggalLahir.setDate(null);
        cmbAgama.setSelectedIndex(0);
        cmbKelasID.setSelectedIndex(0);
        cmbPekerjaan.setSelectedIndex(0);
        rbLaki.isSelected();
    }
    
    private void baca_data_tabel(){
        try{
            st = con.createStatement();
            String tampil = "SELECT tbsiswa.nis AS siswaNIS, tbsiswa.idkelas AS siswaKelas, tbsiswa.th_angkatan as siswaAngkatan,"
                    + "tbsiswa.nama_siswa AS siswaNama, tbsiswa.tanggal_lahir AS siswaTTL, tbsiswa.alamat_siswa AS siswaAlamat,"
                    + "tbsiswa.jenis_kelamin as siswaJekel, tbsiswa.agama_siswa AS siswaAgama, tbortu.nama_ortu AS ortuNama, tbortu.pekerjaan AS ortuPekerjaan,"
                    + "tbortu.alamat AS ortuAlamat, tbortu.telfon AS ortuTelfon FROM tbsiswa, tbortu WHERE tbsiswa.nis = tbortu.nis";
            rs = st.executeQuery(tampil);
            ResultSetMetaData metaData = (ResultSetMetaData) rs.getMetaData();
            int col = metaData.getColumnCount();
            int baris = 0;
            while(rs.next()){
                baris = rs.getRow();
            }
            dTabel = new Object[baris][col];
            int x = 0;
            rs.beforeFirst();
            while(rs.next()){
                dTabel[x][0] = rs.getString("siswaNIS");
                dTabel[x][1] = rs.getString("siswaKelas");
                dTabel[x][2] = rs.getInt("siswaAngkatan");
                dTabel[x][3] = rs.getString("siswaNama");
                dTabel[x][4] = rs.getDate("siswaTTL");
                dTabel[x][5] = rs.getString("siswaAlamat");
                dTabel[x][6] = rs.getString("siswaJekel");
                dTabel[x][7] = rs.getString("siswaAgama");
                dTabel[x][8] = rs.getString("ortuNama");
                dTabel[x][9] = rs.getString("ortuPekerjaan");
                dTabel[x][10] = rs.getString("ortuAlamat");
                dTabel[x][11] = rs.getString("ortuTelfon");
                x++;
            }
            tabelSiswaObjek.setModel(new DefaultTableModel(dTabel, colom));
            
            int[] lebar = {80,100,100,150,150,180,80,120,150,130,180,120};
            tabelSiswaObjek.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            int kolom = tabelSiswaObjek.getColumnCount();
            for(int z = 0; z < kolom; z++){
                javax.swing.table.TableColumn tableColumn = 
                        tabelSiswaObjek.getColumnModel().getColumn(z);
                tableColumn.setPreferredWidth(lebar[z]);
            }
        }catch(Exception e){
            System.out.println(e);
            e.printStackTrace();
        }
    }
    
    
}
