/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mataPelajaran.java
 *
 * Created on 15 Jun 13, 12:46:32
 */

package form;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class mataPelajaran extends javax.swing.JInternalFrame {
    
    Connection con;
    Statement st;
    ResultSet rs;
    
    DefaultTableModel tableModel = new DefaultTableModel();
    private String[] colom = {"No Urut","Kode Mata Pelajaran","Mata Pelajaran","Jumlah Pertemuan"};
    private Object[][] dTabel = null;
    
    /** Creates new form mataPelajaran */
    public mataPelajaran() {
        initComponents();
        baca_data();
        nomor_urut_otomatis();
        tampil_data();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbMapel = new javax.swing.JComboBox();
        txtKode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNoUrut = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtJumper = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMapel = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("Data Mata Pelajaran");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36));
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("MATA PELAJARAN ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Mata Pelajaran "));

        jLabel2.setText("Nama Mata Pelajaran");

        jLabel3.setText("Kode");

        cmbMapel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih Mata Pelajaran ---", "Pendidikan Agama Islam", "PKn", "Matematika", "Bahasa Indonesia", "IPA", "IPS", "Bahasa Inggris", "TIk", "Penjaskes", "Mulok" }));
        cmbMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMapelActionPerformed(evt);
            }
        });

        jLabel4.setText("No Urut");

        txtNoUrut.setEditable(false);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel6.setText("Jumlah Pertemuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNoUrut))
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJumper)
                            .addComponent(txtKode)
                            .addComponent(cmbMapel, 0, 208, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHapus, btnSimpan, btnUpdate, jButton1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtJumper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        tabelMapel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Urut", "Mata Pelajaran", "Kode", "Jumlah Pert"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelMapel.setToolTipText("Tabel Data Mata Pelajaran");
        tabelMapel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMapelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMapel);
        tabelMapel.getColumnModel().getColumn(0).setResizable(false);
        tabelMapel.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabelMapel.getColumnModel().getColumn(1).setResizable(false);
        tabelMapel.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabelMapel.getColumnModel().getColumn(2).setResizable(false);
        tabelMapel.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelMapel.getColumnModel().getColumn(3).setResizable(false);
        tabelMapel.getColumnModel().getColumn(3).setPreferredWidth(80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(437, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmbMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMapelActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbMapelActionPerformed

private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
// TODO add your handling code here:
    String kode = txtKode.getText();
    String jampel = txtJumper.getText();
    String urut = txtNoUrut.getText();
    String mapel = "";
    if(cmbMapel.getSelectedIndex() == 1){
        mapel = "Pendidikan Agama Islam";
    }else if(cmbMapel.getSelectedIndex() == 2){
        mapel = "PKn";
    }else if(cmbMapel.getSelectedIndex() == 3){
        mapel = "Matematika";
    }else if(cmbMapel.getSelectedIndex() == 4){
        mapel = "Bahasa Indonesia";
    }else if(cmbMapel.getSelectedIndex() == 5){
        mapel = "IPA";
    }else if(cmbMapel.getSelectedIndex() == 6){
        mapel = "IPS";
    }else if(cmbMapel.getSelectedIndex() == 7){
        mapel = "Bahasa Inggris";
    }else if(cmbMapel.getSelectedIndex() == 8){
        mapel = "TIK";
    }else if(cmbMapel.getSelectedIndex() == 9){
        mapel = "Penjaskes";
    }else{
        mapel = "Mulok";
    }
    if(cmbMapel.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Mata Pelajaran Harus Dipilih","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }else if(txtKode.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Kode Tidak Boleh Kosong","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtKode.requestFocus();
    }else if(txtJumper.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Masukkan Jumlah Jam Pertemuan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtJumper.requestFocus();
    }else{
        try{
            st = con.createStatement();
            String simpan = "INSERT INTO tbmapel VALUES ('"+Integer.parseInt(urut)+"','"+kode+"','"+mapel+"','"+jampel+"')";
            st.executeUpdate(simpan);
            JOptionPane.showMessageDialog(null, "Tersimpan.","Informasi",JOptionPane.INFORMATION_MESSAGE);
            mati();
            tampil_data();
            nomor_urut_otomatis();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Disimpan","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }
}//GEN-LAST:event_btnSimpanActionPerformed

private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
// TODO add your handling code here:
    int confirmasi = JOptionPane.showConfirmDialog(null, 
            "Yakin Ingin Menghapus Data Ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
    if(confirmasi == 0){
        try{
            st = con.createStatement();
            String hapus = "DELETE FROM tbmapel WHERE kode_mapel = "
                    + "'"+tabelMapel.getValueAt(tabelMapel.getSelectedRow(), 1).toString() +"'";
            st.executeUpdate(hapus);
            JOptionPane.showMessageDialog(null, "Berhasil Dihapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
            tampil_data();
            nomor_urut_otomatis();
            mati();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Dihapus. Pilih Item Terlebih Dahulu","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }
}//GEN-LAST:event_btnHapusActionPerformed

private void tabelMapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMapelMouseClicked
// TODO add your handling code here:
        try{
            
            int rows = tabelMapel.getSelectedRow();
            String tampil = (tabelMapel.getModel().getValueAt(rows, 1).toString());
            String sql = "select * from tbmapel where kode_mapel ='"+tampil+"'";
            st = con.prepareStatement(tampil);
            rs = st.executeQuery(sql);
            if(rs.next()){
                String add1 = rs.getString("nourut");
                txtNoUrut.setText(add1);
                String add2 = rs.getString("kode_mapel");
                txtKode.setText(add2);
                if(rs.getString("mapel").equals("Pendidikan Agama Islam")){
                    cmbMapel.setSelectedIndex(1);
                }else if(rs.getString("mapel").equals("PKn")){
                    cmbMapel.setSelectedIndex(2);
                }else if(rs.getString("mapel").equals("Matematika")){
                    cmbMapel.setSelectedIndex(3);
                }else if(rs.getString("mapel").equals("Bahasa Indonesia")){
                    cmbMapel.setSelectedIndex(4);
                }else if(rs.getString("mapel").equals("IPA")){
                    cmbMapel.setSelectedIndex(5);
                }else if(rs.getString("mapel").equals("IPS")){
                    cmbMapel.setSelectedIndex(6);
                }else if(rs.getString("mapel").equals("Bahasa Inggris")){
                    cmbMapel.setSelectedIndex(7);
                }else if(rs.getString("mapel").equals("TIk")){
                    cmbMapel.setSelectedIndex(8);
                }else if(rs.getString("mapel").equals("Penjaskes")){
                    cmbMapel.setSelectedIndex(9);
                }else if(rs.getString("mapel").equals("Mulok")){
                    cmbMapel.setSelectedIndex(10);
                }
                String add3 = rs.getString("jumlah_pertemuan");
                txtJumper.setText(add3);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
}//GEN-LAST:event_tabelMapelMouseClicked

private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
// TODO add your handling code here:
    String kode = txtKode.getText();
    String jampel = txtJumper.getText();
    String urut = txtNoUrut.getText();
    String mapel = "";
    if(cmbMapel.getSelectedIndex() == 1){
        mapel = "Pendidikan Agama Islam";
    }else if(cmbMapel.getSelectedIndex() == 2){
        mapel = "PKn";
    }else if(cmbMapel.getSelectedIndex() == 3){
        mapel = "Matematika";
    }else if(cmbMapel.getSelectedIndex() == 4){
        mapel = "Bahasa Indonesia";
    }else if(cmbMapel.getSelectedIndex() == 5){
        mapel = "IPA";
    }else if(cmbMapel.getSelectedIndex() == 6){
        mapel = "IPS";
    }else if(cmbMapel.getSelectedIndex() == 7){
        mapel = "Bahasa Inggris";
    }else if(cmbMapel.getSelectedIndex() == 8){
        mapel = "TIK";
    }else if(cmbMapel.getSelectedIndex() == 9){
        mapel = "Penjaskes";
    }else{
        mapel = "Mulok";
    }
    if(txtKode.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Kode Tidak Boleh Kosong","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtKode.requestFocus();
    }else if(cmbMapel.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Mata Pelajaran Harus Dipilih","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }else if(txtJumper.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Masukkan Jumlah Jam Pertemuan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        txtJumper.requestFocus();
    }else{
        try{
            st = con.createStatement();
            String simpan = "UPDATE tbmapel SET nourut= '"+urut+"',"
                    + "kode_mapel = '"+kode+"',mapel = '"+mapel+"',jumlah_pertemuan = '"+jampel+"'"
                    + " Where nourut = '"+urut+"'";
            st.executeUpdate(simpan);
            JOptionPane.showMessageDialog(null, "Terupdate.","Informasi",JOptionPane.INFORMATION_MESSAGE);
            mati();
            tampil_data();
            nomor_urut_otomatis();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Diupdate","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }
}//GEN-LAST:event_btnUpdateActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbMapel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelMapel;
    private javax.swing.JTextField txtJumper;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNoUrut;
    // End of variables declaration//GEN-END:variables

    private void nomor_urut_otomatis(){
        try{
            st = con.createStatement();
            rs = st.executeQuery("select nourut from tbmapel");
            int baris = 0;
            while(rs.next()){
                baris = rs.getRow();
            }
            if (baris == 0){
                txtNoUrut.setText("0001");
            } else {
                int nom = baris+1;
                if(nom < 10){
                    txtNoUrut.setText("000"+nom);
                }else if(nom < 100){
                    txtNoUrut.setText("00"+nom);
                }else if(nom < 1000){
                    txtNoUrut.setText("0"+nom);
                }else if(nom < 10000){
                    txtNoUrut.setText(""+nom);
                }    
            }
            rs.close();
        }catch(Exception e){
            System.out.println("Error "+e);
        }
    }
    
    private void baca_data(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost/visual", "root", "");
            st = con.createStatement();            
            System.out.println("Koneksi Sukses");
        } catch (SQLException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tampil_data(){
         try{
            
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM tbmapel");
            ResultSetMetaData meta_barang = rs.getMetaData();
            int col = meta_barang.getColumnCount();
            int baris = 0;
            while(rs.next()){
                baris = rs.getRow();
            }
            dTabel = new Object[baris][col];
            int x = 0;
            rs.beforeFirst();
            while(rs.next()){
                dTabel[x][0] = rs.getString("nourut");
                dTabel[x][1] = rs.getString("kode_mapel");
                dTabel[x][2] = rs.getString("mapel");
                dTabel[x][3] = rs.getString("jumlah_pertemuan");
                x++;
            }
            tabelMapel.setModel(new DefaultTableModel(dTabel,colom));
            int lebar[] = {80, 150, 170, 100};
            int kolom = tabelMapel.getColumnCount();
            for(int z = 0; z < kolom; z++){
                javax.swing.table.TableColumn tableColumn = 
                        tabelMapel.getColumnModel().getColumn(z);
                tableColumn.setPreferredWidth(lebar[z]);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error Memuat Database", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void mati(){
        txtJumper.setText(null);
        txtKode.setText(null);
        txtNoUrut.setText(null);
        cmbMapel.setSelectedIndex(0);
    }
    
}
