/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pengaturanAkun.java
 *
 * Created on Jul 2, 2013, 1:13:36 PM
 */
package form;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dj_Ubet
 */
public class pengaturanAkun extends javax.swing.JInternalFrame {
    
    Connection con;
    Statement st;
    ResultSet rs;
    
    /** Creates new form pengaturanAkun */
    public pengaturanAkun() {
        initComponents();
        baca_data();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JPasswordField();
        txtPassword2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cmbLevel = new javax.swing.JComboBox();
        buttonSimpan = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtpasswordCek = new javax.swing.JPasswordField();
        btnUserBaru = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pengaturan Akun");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tambah User"));

        jLabel1.setText("UserName");

        jLabel2.setText("Password");

        jLabel3.setText("Confirmasi Password");

        txtUser.setEnabled(false);

        txtPassword1.setEnabled(false);

        txtPassword2.setEnabled(false);

        jLabel4.setText("Level");

        cmbLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih Level ---", "Admin", "Kepala", "User" }));
        cmbLevel.setEnabled(false);

        buttonSimpan.setText("Update Data");
        buttonSimpan.setEnabled(false);

        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        jLabel5.setText("Masukkan Password");

        btnUserBaru.setText("Simpan User Baru");
        btnUserBaru.setEnabled(false);
        btnUserBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserBaruActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtpasswordCek, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCek))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCancel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUserBaru)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSimpan))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPassword2)
                                .addComponent(txtPassword1)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpasswordCek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCek))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(btnUserBaru)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnUserBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserBaruActionPerformed
// TODO add your handling code here:
    Hidup();
    txtpasswordCek.setEnabled(false);
    btnCek.setEnabled(false);
    txtpasswordCek.setText(null);
    int kode;
    if(cmbLevel.getSelectedIndex() == 1){
        kode = 1;
    }else if(cmbLevel.getSelectedIndex() == 2){
        kode = 2;
    }else{
        kode = 3;
    }
    String user = txtUser.getText();
    String pass2 = txtPassword2.getText();
    String pass = txtPassword1.getText(); 
    try{
        if( pass == pass2){
            st = con.createStatement();
            String sql = "INSERT INTO tbuser VALUES ('"+user+"','"+pass+",'"+kode+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "User Baru Tersimpan.","Informasi",JOptionPane.INFORMATION_MESSAGE);
            txtUser.setText(null);
            txtPassword1.setText(null);
            txtPassword2.setText(null);
        }else{
            JOptionPane.showMessageDialog(null, "Password Konfirmasi Salah","Peringatan",JOptionPane.WARNING_MESSAGE);
            txtPassword1.setText(null);
            txtPassword2.setText(null);
            txtPassword1.requestFocus();
        }
   }catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Simpan Gagal.","Error",JOptionPane.ERROR_MESSAGE);
   }
}//GEN-LAST:event_btnUserBaruActionPerformed

private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
// TODO add your handling code here:
    try{
        st = con.createStatement();
        String sql = "SELECT password FROM tbuser where password = '"+txtpasswordCek.getText()+"'";
        rs = st.executeQuery(sql);
        int baris = 0;
        while(rs.next()){
            baris = rs.getRow();
        }
        if(baris == 1){
            JOptionPane.showMessageDialog(null, "Terkonfirmasi.","Informasi",JOptionPane.INFORMATION_MESSAGE);
            Hidup();
            txtpasswordCek.setEnabled(false);
            txtpasswordCek.setText(null);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid User/Password.","Informasi",JOptionPane.ERROR_MESSAGE);
            txtpasswordCek.requestFocus();
            txtpasswordCek.setText(null);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Invalid User/Password","Error",JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}//GEN-LAST:event_btnCekActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
// TODO add your handling code here:
    mati();
    txtpasswordCek.setEnabled(true);
    btnCek.setEnabled(true);
    txtpasswordCek.setText(null);
}//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnUserBaru;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox cmbLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPasswordField txtpasswordCek;
    // End of variables declaration//GEN-END:variables

    private void baca_data(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost/visual", "root", "");
            st = con.createStatement();            
            System.out.println("Koneksi Sukses");
        } catch (SQLException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void mati(){
        txtUser.setEnabled(false);
        txtPassword1.setEnabled(false);
        txtPassword2.setEnabled(false);
        cmbLevel.setEnabled(false);
        buttonSimpan.setEnabled(false);
        //tAkun.setEnabled(false);
        btnUserBaru.setEnabled(false);
        btnCancel.setEnabled(false);
    }
    
    private void Hidup(){
        txtUser.setEnabled(true);
        txtPassword1.setEnabled(true);
        txtPassword2.setEnabled(true);
        cmbLevel.setEnabled(true);
        buttonSimpan.setEnabled(true);
        //tAkun.setEnabled(true);
        btnUserBaru.setEnabled(true);
        btnCancel.setEnabled(true);
    }
    
}
